---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- name: Create the system group
  group:
    name: "{{ searchlight_system_group_name }}"
    state: "present"
    system: "yes"

- name: Create the searchlight system user
  user:
    name: "{{ searchlight_system_user_name }}"
    group: "{{ searchlight_system_group_name }}"
    comment: "{{ searchlight_system_comment }}"
    shell: "{{ searchlight_system_shell }}"
    system: "yes"
    createhome: "yes"
    home: "{{ searchlight_system_user_home }}"

- name: Create searchlight dirs
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner|default(searchlight_system_user_name) }}"
    group: "{{ item.group|default(searchlight_system_group_name) }}"
    mode: "{{ item.mode|default('0755') }}"
  with_items:
    - { path: "/openstack", owner: "root", group: "root" }
    - { path: "/etc/searchlight" }
    - { path: "{{ searchlight_system_user_home }}" }
    - { path: "/var/lib/searchlight/tmp" }
    - { path: "/var/lib/searchlight/locks" }
    - { path: "/var/cache/searchlight", mode: "0700" }

- name: Test for log directory or link
  shell: |
    if [ -h "/var/log/searchlight"  ]; then
      chown -h {{ searchlight_system_user_name }}:{{ searchlight_system_group_name }} "/var/log/searchlight"
      chown -R {{ searchlight_system_user_name }}:{{ searchlight_system_group_name }} "$(readlink /var/log/searchlight)"
    else
      exit 1
    fi
  register: log_dir
  failed_when: false
  changed_when: log_dir.rc != 0

- name: Create searchlight log dir
  file:
    state: directory
    owner: "{{ searchlight_system_user_name }}"
    group: "{{ searchlight_system_group_name }}"
    mode: "0755"
    path: "/var/log/searchlight" 
  when: log_dir.rc != 0
